package br.com.supera.smartiot.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MeterAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMeterAllPropertiesEquals(Meter expected, Meter actual) {
        assertMeterAutoGeneratedPropertiesEquals(expected, actual);
        assertMeterAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMeterAllUpdatablePropertiesEquals(Meter expected, Meter actual) {
        assertMeterUpdatableFieldsEquals(expected, actual);
        assertMeterUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMeterAutoGeneratedPropertiesEquals(Meter expected, Meter actual) {
        assertThat(expected)
            .as("Verify Meter auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMeterUpdatableFieldsEquals(Meter expected, Meter actual) {
        assertThat(expected)
            .as("Verify Meter relevant properties")
            .satisfies(e -> assertThat(e.getSerialNumber()).as("check serialNumber").isEqualTo(actual.getSerialNumber()))
            .satisfies(e -> assertThat(e.getLocation()).as("check location").isEqualTo(actual.getLocation()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMeterUpdatableRelationshipsEquals(Meter expected, Meter actual) {}
}
