package br.com.supera.feedback360.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SysRoleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSysRoleAllPropertiesEquals(SysRole expected, SysRole actual) {
        assertSysRoleAutoGeneratedPropertiesEquals(expected, actual);
        assertSysRoleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSysRoleAllUpdatablePropertiesEquals(SysRole expected, SysRole actual) {
        assertSysRoleUpdatableFieldsEquals(expected, actual);
        assertSysRoleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSysRoleAutoGeneratedPropertiesEquals(SysRole expected, SysRole actual) {
        assertThat(expected)
            .as("Verify SysRole auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSysRoleUpdatableFieldsEquals(SysRole expected, SysRole actual) {
        assertThat(expected)
            .as("Verify SysRole relevant properties")
            .satisfies(e -> assertThat(e.getRoleName()).as("check roleName").isEqualTo(actual.getRoleName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSysRoleUpdatableRelationshipsEquals(SysRole expected, SysRole actual) {}
}
