# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: smartiot
services:
  app:
    image: public.ecr.aws/amazoncorretto/amazoncorretto:latest
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://smartiot.czeieuicka0a.us-east-1.rds.amazonaws.com:3306/smartiot?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
      - SPRING_LIQUIBASE_URL=jdbc:mysql://smartiot.czeieuicka0a.us-east-1.rds.amazonaws.com:3306/smartiot?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
    ports:
      - 127.0.0.1:29090:29090
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:29090/management/health
      interval: 5s
      timeout: 5s
      retries: 40
